#!/usr/bin/env bash
cd /tRecX
./tRecX tutorial/00HarmonicOsc1.inp
./tRecX tutorial/00HarmonicOsc1.inp
./tRecX tutorial/01HarmonicOsc2.inp
./tRecX tutorial/02HarmonicOscPolar.inp
./tRecX tutorial/03HydrogenPolar.inp
./tRecX tutorial/04Hyd1d.inp
./tRecX tutorial/05irECS.inp
./tRecX tutorial/06TimeProp.inp
./tRecX tutorial/07HighHarmonicGeneration.inp
./tRecX tutorial/08Hyd1dSpectrum.inp
./tRecX tutorial/09HydrogenSpectrum.inp
./tRecX tutorial/10IRSpectrum.inp
./tRecX tutorial/15Elliptic400nm.inp
./tRecX tutorial/15TayloredField.inp
./tRecX tutorial/21Helium2dIR.inp
./tRecX tutorial/23Helium3DSpectrum.inp
./tRecX tutorial/90Floquet.inp
