// tRecX = tSurff+irECS - a universal Schroedinger solver
// Copyright (c) 2015 - 2021 by Armin Scrinzi (armin.scrinzi@lmu.de)
// 
// This program is free software; you can redistribute it and/or modify it 
// under the terms of the GNU General Public License as published by the Free Software Foundation; 
// either version 2 of the License, or (at your option) any later version.
// End of license
 
#include "basicDisc.h"

//resolve forward declarations
//#include "basisFctsHeader.h"
#include "index.h"
#include "multiIndex.h"
#include "basisAbstract.h"
//#include "basisMat.h"
#include "operatorData.h"
#include "coordinate.h"

#include "readInput.h"
#include "printOutput.h"
#include "axis.h"
#include "tools.h"
#include "abort.h"
#ifdef _USE_HACC_
#include "quantumChemicalInput.h"
#endif
#include "axisTree.h"
#include "overlapDVR.h"

using namespace std;
#include "eigenNames.h"


///  General Discretization: names and discretizaion parameters are specified on input
///    a range of names is available: radial, angles, cartesian, discrete numbers like L or M
///    set Test() for application examples
///

BasicDisc::BasicDisc(ReadInput &In, const string &Subset, const IndexConstraint* Constraint)
{
    In.obsolete("Integration","DVR","DVR is enforced - cannot be chosen externally");
    constraint = Constraint;
    setAxis(In,Subset);

    if(Subset==""){
        int line(1);
        _axisTree.reset(new AxisTree(In,line));
    }

    if(axis.size()>0){
#ifdef _USE_HACC_
        // need to set up chemistry data before axes can be
        if(axis[0].name=="Ion")QuantumChemicalInput::read(In);
#endif
        construct();

    }
}

BasicDisc::BasicDisc(std::vector<Axis> Ax, const IndexConstraint *Constraint)
{
    if(Ax.size()==0)ABORT("no axes given");
    axis=Ax;
    constraint = Constraint;

    for(unsigned int n=0;n<axis.size();n++){
        hierarchy.push_back(axis[n].coor.name());
        if((axis[n].basDef.size()>1 and axis[n].basDef[0].name()=="useIndex"))DEVABORT("\"useIndex\" is obsolet, use \"vector\" instead")
        if((axis[n].basDef.size()>1 and axis[n].basDef[0].name()!="vector") or
                (axis[n].basDef.size()==1 and axis[n].basDef[0].name().find("grid") != string::npos))
            continuityLevel.push_back(n); // multiple elements require continuity
        if(n>0)name+=".";
        name+=axis[n].name;
    }
    construct();
}

BasicDisc::BasicDisc(std::string InputFile)
{
    ReadInput in=ReadInput(InputFile);
    in.obsolete("Integration","DVR","DVR is enforced - cannot be chosen externally");
    setAxis(in);
    construct();
}

std::string BasicDisc::generateTestInputs(int argc, char *argv[], int Dim){

    string inpFile;
    if(argc>0){
        inpFile=string(argv[0]);
        inpFile+=".inp";
        string inp;
        for(int k=0;k<argc;k++){
            if(argv[k][0]!='-')inp=argv[k];
            if(inp.find(".inp")==inp.length()-4)inpFile=inp;
        }
        inpFile=generateTestInputs(inpFile,Dim);
    }
    else {
        inpFile=generateTestInputs("",Dim);
    }
    return inpFile;
}

std::string BasicDisc::generateTestInputs(string InpFile, int Dim){
    if(Dim>3)ABORT(Str("only 1d - 3d are defined, is Dim=")+Dim);

    if(InpFile!="");
    else if(Dim==1)InpFile+="test1d.inp";
    else if(Dim==2)InpFile+="test2d.inp";
    else if(Dim==2)InpFile+="test3d.inp";

    if(folder::exists(InpFile)){
        ReadInput old(InpFile);
        if(old.found("Axis")){
            PrintOutput::message("input file \""+InpFile+"\" exists and contains axes --- left unchanged");
            return InpFile;
        }
    }

    ofstream o;
    o.open(InpFile.c_str(),ios_base::app); // append to file
    o<<"\n*** axes automatically generated by generateTestInputs ***"<<endl;
    o<<""<<endl;
    o<<"subsequent axes with the same name will be concatenated"<<endl;

    if(Dim==1){
        o<<"Axis: name,nCoefficients,lower end, upper end,functions,order"<<endl;
        o<<" X,40,-10.,0.,polynomial,10"<<endl;
        o<<" X,40,0.,10.,polynomial,10"<<endl;
    }

    else if(Dim==2){
        o<<""<<endl;
        o<<" a blank axis takes its name from the preceding axis"<<endl;
        o<<""<<endl;
        o<<"Axis: name,nCoefficients,lower end, upper end,functions,order"<<endl;
        o<<" X,8,-5.,0.,polynomial,4"<<endl;
        o<<"  ,8,0.,5.,polynomial,8"<<endl;
        o<<" Y,14,-5.,5.,polynomial,7"<<endl;

    }
    else if(Dim==3){
        o<<"Axis: name,nCoefficients,lower end, upper end,functions,order,complex scaling angle"<<endl;
        o<<" M,1"<<endl;
        o<<" L,1"<<endl;
        o<<" R,100,0.,40.,polynomial,10,0.3"<<endl;
        o<<" R, 50,0.,20.,polynomial,10,0.3"<<endl;
    }

    o<<endl;
    o.close();
    PrintOutput::message("new default axis input in file "+InpFile);

    return InpFile;
}

void BasicDisc::Test(){
    ABORT("adjust for using OperatorTree");
    // 1d harmonic oscillator
    cout<<"\n *** 1d harmonic oscillator ***\n\n";
    generateTestInputs("generalX.inp",1);

    Discretization * X= new BasicDisc("generalX.inp");
    OperatorTree H1("Hamiltonian","+1/2<dJd> +1/2<qJq>",X->idx(),X->idx());
    OperatorTree S1("Overlap","<1>",X->idx(),X->idx());
    vector<complex<double> > eval;
    vector<Coefficients*> evec;
    cout<<endl<<"*** 1d HO done ***************** "<<endl<<endl;

    /// 2d harmonic oscillator
    cout<<"\n *** 2d harmonic oscillator ***\n\n";

    generateTestInputs("generalXY.inp",2);
    Discretization * XY= new BasicDisc("generalXY.inp");
    XY->idx()->testInverseOverlap();
    cout<<"generalXY\n"+XY->idx()->str()<<endl;
    OperatorTree S2("Overlap","<1>",XY->idx(),XY->idx());

    OperatorTree H2("Hamiltonian","2d HO",XY->idx(),XY->idx());
    eval.clear();
    evec.clear();
    cout<<endl<<"*** 2d HO done ***************** "<<endl<<endl;

    /// hydrogen atom
    cout<<"\n *** hydrogen atom ***"<<endl;
    // create input file
    generateTestInputs("generalPolar.inp",3);
    Discretization * MLR= new BasicDisc("generalPolar.inp");
    MLR->idx()->testInverseOverlap();
    OperatorTree SR("Overlap","<1>",MLR->idx(),MLR->idx());
    SR.iIndex->testInverseOverlap();

    OperatorTree HR("Hamiltonian","hydrogen",MLR->idx(),MLR->idx());
    eval.clear();
    evec.clear();
    cout<<endl<<"*** hydrogen done ***************** "<<endl<<endl;

}
