// tRecX = tSurff+irECS - a universal Schroedinger solver
// Copyright (c) 2015 - 2021 by Armin Scrinzi (armin.scrinzi@lmu.de)
// 
// This program is free software; you can redistribute it and/or modify it 
// under the terms of the GNU General Public License as published by the Free Software Foundation; 
// either version 2 of the License, or (at your option) any later version.
// End of license
 
#include "makePlot.h"

#include "algebra.h"
#include "readInput.h"
#include "tools.h"
#include "asciiFile.h"

using namespace std;

MakePlot::MakePlot(ReadInput &Inp)
{
    Inp.read("MakePlot","npoints",_nPoints,"101","number of plot points");
    Inp.read("MakePlot","file",_file,Inp.output()+"makeplots","plot file name");
    string alglist;
    if(not Inp.found("MakePlot"))return;

    Inp.read("MakePlot","algebras",alglist,ReadInput::noDefault,"blank-separated list of algebras");
    Inp.read("MakePlot","xmin",_xMin,ReadInput::noDefault,"lower end of plot range");
    Inp.read("MakePlot","xmax",_xMax,ReadInput::noDefault,"upper end of plot range");

    AsciiFile f(_file);
    vector<string> head;
    head.push_back("generated by MakePlot");
    head.push_back("0: x ="+tools::str(_xMin)+",  "+tools::str(_xMax));
    head.push_back("");
    head.push_back("  ...x...  ");
    vector<std::vector<double> > cols(1,vector<double>());
    double x=_xMin,dx=(_xMax-_xMin)/(_nPoints-1);
    for (int k=0;k<_nPoints;k++,x+=dx)cols[0].push_back(x);
    f.writeComments(head);
    f.writeCols(cols);

    vector<string> alg=tools::splitString(alglist,' ');
    for (int k=0;k<alg.size();k++)addPlot(Algebra(alg[k]));
}


void MakePlot::addPlot(const Algebra &A) const{

    vector<std::vector<double> > cols;
    vector<string> head;
    AsciiFile f(_file);
    f.readComments(head);
    f.readCols(cols);
    cols.resize(cols.size()+2);
    for (int k=0;k<cols[0].size();k++)
    {
        complex<double> v=A.val(cols[0][k]);
        cols[cols.size()-2].push_back(v.real());
        cols[cols.size()-1].push_back(v.imag());
        cout<<"Algebra "<<A.definition()<<" "<<cols[0][k]<<" "<<v<<endl;
    }

    if (tools::anyElement<double>(cols[cols.size()-2],tools::differs,0.)){
        head.insert(head.end()-2,1,tools::str(cols.size()-2)+": (Re) "+A.definition());
        head.back()+=" Re("+A.definition().substr(0,6)+"...) ";
    }
    else
        cols.erase(cols.end()-2);

    if ( tools::anyElement(cols[cols.size()-1],tools::differs,0.)){
        head.insert(head.end()-2,1,tools::str(cols.size()-1)+": (Im) "+A.definition());
        head.back()+=" Im("+A.definition().substr(0,6)+"...) ";
    }
    else
        cols.erase(cols.end()-1);

    f.writeComments(head);
    f.writeCols(cols,5);
}

