# Generated by Django 3.2.8 on 2021-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='compute_resource_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='core_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='group_resource_profile_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='node_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='queue_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='total_physical_memory',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='walltime_limit',
            field=models.IntegerField(null=True),
        ),
    ]
