# Generated by Django 3.2.8 on 2021-11-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0002_auto_20211103_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='epolyscat_django_app.runsroot'),
        ),
    ]
