# Generated by Django 3.2.8 on 2021-12-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epolyscat_django_app', '0003_alter_run_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xaxis', models.CharField(default='', max_length=2)),
                ('yaxes', models.CharField(default='', max_length=20)),
                ('flags', models.CharField(default='', max_length=200)),
                ('last_use', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
