# Generated by Django 3.2.8 on 2022-01-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0005_remoteexecution_airavata_experiment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteexecution',
            name='resource_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
