# Generated by Django 3.2.8 on 2022-01-27 12:24

from django.db import migrations


def create_experiments_for_roots(apps, schema_editor):
    # Find all of the roots and create an experiment for each one with the name
    # matching the root
    RunsRoot = apps.get_model("epolyscat_django_app", "RunsRoot")
    Experiment = apps.get_model("epolyscat_django_app", "Experiment")
    for root in RunsRoot.objects.all():
        experiment, created = Experiment.objects.get_or_create(name=root.root, owner=root.owner, root=root)
        for run in root.runs.all():
            run.experiment = experiment
            run.save()
    # Delete any experiments that don't have a root
    Experiment.objects.filter(root=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("epolyscat_django_app", "0007_experiment_root"),
    ]

    operations = [
        migrations.RunPython(create_experiments_for_roots, migrations.RunPython.noop)
    ]
