# Generated by Django 3.2.8 on 2022-01-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0008_auto_20220127_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epolyscat_django_app.runsroot'),
        ),
    ]
