# Generated by Django 3.2.8 on 2022-01-27 12:49

from django.db import migrations

def set_name_for_runs(apps, schema_editor):
    # Find all of the roots and create an experiment for each one with the name
    # matching the root
    Run = apps.get_model("epolyscat_django_app", "Run")
    for run in Run.objects.all():
        run.name = f"{run.root.root}/{run.number}"
        run.save()

class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0009_auto_20220127_1249'),
    ]

    operations = [
        migrations.RunPython(set_name_for_runs, migrations.RunPython.noop)
    ]
