# Generated by Django 3.2.8 on 2022-01-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0010_auto_20220127_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
