# Generated by Django 3.2.8 on 2022-02-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0011_alter_run_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='name',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='root',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to='epolyscat_django_app.runsroot'),
        ),
    ]
