# Generated by Django 3.2.8 on 2022-03-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0012_auto_20220223_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='input_table',
            field=models.TextField(null=True),
        ),
    ]
