# Generated by Django 3.2.8 on 2022-04-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0013_run_input_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteexecution',
            name='job_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
