# Generated by Django 3.2.8 on 2022-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0014_remoteexecution_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='view',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='view',
            name='type',
            field=models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('default', 'Selected'), ('user-defined', 'User Defined')], default='user-defined', max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='views',
            field=models.ManyToManyField(related_name='runs', to='epolyscat_django_app.View'),
        ),
    ]
