# Generated by Django 3.2.18 on 2025-09-16 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epolyscat_django_app', '0016_auto_20220506_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['root__root', 'number']},
        ),
        migrations.AlterField(
            model_name='experiment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epolyscat_experiments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plotparameters',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epolyscat_plotparameters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='runsroot',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epolyscat_runsroots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='view',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epolyscat_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='view',
            name='type',
            field=models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('default', 'Selected'), ('user-defined', 'User Defined'), ('tutorial', 'Tutorial')], default='user-defined', max_length=20),
        ),
    ]
