# Generated by Django 3.2.18 on 2025-11-15 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epolyscat_django_app', '0017_auto_20250916_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='airavata_project_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='description',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='run',
            name='directory',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='run',
            name='is_email_notification_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='runs', to='epolyscat_django_app.View'),
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=240)),
                ('value', models.CharField(max_length=240, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='epolyscat_django_app.run')),
            ],
            options={
                'unique_together': {('run', 'type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_product_uri', models.CharField(max_length=100)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='epolyscat_django_app.input')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=4000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('airavata_project_id', models.CharField(max_length=255, null=True, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epolyscat_project_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'owner')},
            },
        ),
    ]
