# Generated by Django 3.2.18 on 2025-12-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0018_auto_20251115_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={},
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='root',
        ),
        migrations.AlterUniqueTogether(
            name='run',
            unique_together=set(),
        ),
    ]
