# Generated by Django 3.2.18 on 2025-12-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0019_auto_20251203_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['root__root', 'number']},
        ),
        migrations.AlterUniqueTogether(
            name='run',
            unique_together={('number', 'root')},
        ),
    ]
