# Generated by Django 3.2.18 on 2025-12-03 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epolyscat_django_app', '0020_auto_20251203_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epolyscat_run', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='run',
            unique_together={('name', 'owner')},
        ),
    ]
