# Generated by Django 3.2.18 on 2025-12-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epolyscat_django_app', '0021_auto_20251203_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='run',
            unique_together=set(),
        ),
    ]
