# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epolyscat_django_app", "0023_auto_20260617_1802"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="run_mode",
            field=models.CharField(
                choices=[
                    ("module", "Module"),
                    ("workflow", "Workflow"),
                    ("utility", "Utility"),
                ],
                default="module",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="workflow_stage",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="run",
            name="workflow_application",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="run",
            name="workflow_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
