# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epolyscat_django_app", "0024_run_workflow_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="module_application",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="run",
            name="utility_application",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
