# Generated by Codex on 2026-07-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("epolyscat_django_app", "0025_run_application_selectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="parent_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_steps",
                to="epolyscat_django_app.run",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="workflow_step_order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="workflow_step_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
